# This file was generated by GoReleaser. DO NOT EDIT.
cask "spicedb" do
  version "1.56.1"

  on_macos do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_amd64.tar.gz"
      sha256 "073368919ac502c1e413492366f3f067386f8c1b28c6a707c1fe556a3153ae64"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_arm64.tar.gz"
      sha256 "6448972eac45396e5a1b527255f5794f602d5a623e5a58d989c04f529ae5fd17"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_amd64.tar.gz"
      sha256 "91d8f1029eacc92fe6f1011ac3ef9c4af934a88461f424fc3dfb31fb75374a4c"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_arm64.tar.gz"
      sha256 "4277d472bd6e965626f0c9e16530569f23ecc210ebcfcd25c97808c8f860068c"
    end
  end

  name "spicedb"
  desc "Google Zanzibar-inspired permissions database for fine-grained access control"
  homepage "https://github.com/authzed/spicedb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spicedb"
  manpage "manpages/spicedb.1"
  bash_completion "completions/spicedb.bash"
  fish_completion "completions/spicedb.fish"
  zsh_completion "completions/spicedb.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spicedb"]
    end
  end

  # No zap stanza required

end
