# This file was generated by GoReleaser. DO NOT EDIT.
cask "spicedb@1.54.0" do
  version "1.54.0"

  on_macos do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_amd64.tar.gz"
      sha256 "f99e1c15bc411d066e7d2dd1a700a97c768f9f645e5827972c2603b29c8f2a63"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_arm64.tar.gz"
      sha256 "af91d56cc8093f5dd003ef21fb46715c7803ec3c6b81a30f25bf5d05a2881ec7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_amd64.tar.gz"
      sha256 "ba276d5c7e222dfdd06700a1514f614e38a4bd95eccbe2be129433155d8a7c9b"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_arm64.tar.gz"
      sha256 "b58da5caabcfe6ebed6a5f1b875ca0c59655e3787d01b9f03db722f1c33ea3ad"
    end
  end

  name "spicedb@1.54.0"
  desc "Google Zanzibar-inspired permissions database for fine-grained access control"
  homepage "https://github.com/authzed/spicedb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spicedb"
  manpage "manpages/spicedb.1"
  bash_completion "completions/spicedb.bash"
  fish_completion "completions/spicedb.fish"
  zsh_completion "completions/spicedb.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spicedb"]
    end
  end

  # No zap stanza required

end
