# This file was generated by GoReleaser. DO NOT EDIT.
cask "spicedb@1.52.0" do
  version "1.52.0"

  on_macos do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_amd64.tar.gz"
      sha256 "24cb41313d65d428e3061e2f0ed0a94d6b8b30643a0c471edb3cadbee9075515"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_arm64.tar.gz"
      sha256 "b6b62ca1b68b9472eef987397a362806a9d25a43b5a23290ba250bb7deb4577c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_amd64.tar.gz"
      sha256 "7897dc9dc3f5dc2308e7e1d710294afc69fe719e4e92ef51b9d2446ee84fe0dc"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_arm64.tar.gz"
      sha256 "f9176f29cd48a011890f6496a9577a620c76c6de039a907cd60b30ac2c512ce1"
    end
  end

  name "spicedb@1.52.0"
  desc "Google Zanzibar-inspired permissions database for fine-grained access control"
  homepage "https://github.com/authzed/spicedb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spicedb"
  manpage "manpages/spicedb.1"
  bash_completion "completions/spicedb.bash"
  fish_completion "completions/spicedb.fish"
  zsh_completion "completions/spicedb.zsh"

  # No zap stanza required

end
