# This file was generated by GoReleaser. DO NOT EDIT.
cask "spicebox" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/authzed/spicebox/releases/download/v#{version}/spicebox_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/authzed/spicebox"
      sha256 "f684bca09b3b84e0daa61e2dd067305bd8af3cb94d4b4a23ebda65c778987ac8"
    end
    on_arm do
      url "https://github.com/authzed/spicebox/releases/download/v#{version}/spicebox_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/authzed/spicebox"
      sha256 "dcc751586cc6357f1bcc2c9957543868246a735759269e4bdcb7ae39b8b27eac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/authzed/spicebox/releases/download/v#{version}/spicebox_#{version}_linux_amd64.tar.gz",
        verified: "github.com/authzed/spicebox"
      sha256 "19f60d54555c9ac345de35eb6b6b618d1c01d228addd710e8d940ee241ee18b5"
    end
    on_arm do
      url "https://github.com/authzed/spicebox/releases/download/v#{version}/spicebox_#{version}_linux_arm64.tar.gz",
        verified: "github.com/authzed/spicebox"
      sha256 "71a9d55cc29e617a2fbeff4ef732b4fbee16f7d456e23db6187c579da6903ee2"
    end
  end

  name "spicebox"
  desc "Fine-grained permissions and sandboxing for AI coding agents, powered by SpiceDB"
  homepage "https://github.com/authzed/spicebox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spicebox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spicebox"]
    end
  end

  # No zap stanza required

end
