# This file was generated by GoReleaser. DO NOT EDIT.
cask "spicedb@1.56.0" do
  version "1.56.0"

  on_macos do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_amd64.tar.gz"
      sha256 "d2f4a4a86d5ff8ee8506e53c47f784373f4703720f9ebb37b7ac07bc2f809319"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_arm64.tar.gz"
      sha256 "44fadb7c5db474f72987834f9f9abc8d643c031abc6b2f2fa3b3ffcd5028defe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_amd64.tar.gz"
      sha256 "70324e81f85dd5f6177a31b2e08915d7db70b5d29cbd7955c7b14dfce5abeed0"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_arm64.tar.gz"
      sha256 "0511f1bc4c1f772ca38861e432a11933859ebafc1cf1cc0db73dd324e9a38f41"
    end
  end

  name "spicedb@1.56.0"
  desc "Google Zanzibar-inspired permissions database for fine-grained access control"
  homepage "https://github.com/authzed/spicedb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spicedb"
  manpage "manpages/spicedb.1"
  bash_completion "completions/spicedb.bash"
  fish_completion "completions/spicedb.fish"
  zsh_completion "completions/spicedb.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spicedb"]
    end
  end

  # No zap stanza required

end
