# This file was generated by GoReleaser. DO NOT EDIT.
cask "spicedb" do
  version "1.53.0"

  on_macos do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_amd64.tar.gz"
      sha256 "540ebdb281f6c4f18542d3fc64ee09d421046a87c2d2ad93f6a504cf6971f3a1"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_darwin_arm64.tar.gz"
      sha256 "0e2e4ed5b859d31ef76ee41624dd5dd70ebb0d6ee0aa931edaa18ccbc9583ef3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_amd64.tar.gz"
      sha256 "d016e3f378ae0002c545a228dc104e52fb39851228a0d8dfc6195a5b394088c0"
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v#{version}/spicedb_#{version}_linux_arm64.tar.gz"
      sha256 "824c0161c900f8ec47155f1f3ca3974d3a22a34afb9b7df10b5cae10fe415065"
    end
  end

  name "spicedb"
  desc "Google Zanzibar-inspired permissions database for fine-grained access control"
  homepage "https://github.com/authzed/spicedb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spicedb"
  manpage "manpages/spicedb.1"
  bash_completion "completions/spicedb.bash"
  fish_completion "completions/spicedb.fish"
  zsh_completion "completions/spicedb.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spicedb"]
    end
  end

  # No zap stanza required

end
