# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpicedbAT1330 < Formula
  desc "SpiceDB is a Zanzibar-inspired database that stores, computes, and validates application permissions."
  homepage "https://authzed.com/"
  version "1.33.0"
  license "Apache-2.0"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/authzed/spicedb/releases/download/v1.33.0/spicedb_1.33.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "04ae90115b75d8a34b2457ecb9adb8b0729631fa3c004408cd25b2bd8028a288"

      def install
        if !File.exists? "spicedb"
          system "go build --ldflags \"-s -w -X github.com/jzelinskie/cobrautil/v2.Version=$(git describe --always --abbrev=7 --dirty --tags)\" ./cmd/spicedb"
        end
        bin.install "spicedb"
        bash_completion.install "completions/spicedb.bash" => "spicedb"
        zsh_completion.install "completions/spicedb.zsh" => "_spicedb"
        fish_completion.install "completions/spicedb.fish"
      end
    end
    on_arm do
      url "https://github.com/authzed/spicedb/releases/download/v1.33.0/spicedb_1.33.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "245bb4bbf98093d625f786d1f5d034f9a7090cfe82247afc6b9764e20c9e280b"

      def install
        if !File.exists? "spicedb"
          system "go build --ldflags \"-s -w -X github.com/jzelinskie/cobrautil/v2.Version=$(git describe --always --abbrev=7 --dirty --tags)\" ./cmd/spicedb"
        end
        bin.install "spicedb"
        bash_completion.install "completions/spicedb.bash" => "spicedb"
        zsh_completion.install "completions/spicedb.zsh" => "_spicedb"
        fish_completion.install "completions/spicedb.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/authzed/spicedb/releases/download/v1.33.0/spicedb_1.33.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "39055ce2ec300630a3fffa8eb790f49382a1575623e12ce37a604b51b42b2ece"

        def install
          if !File.exists? "spicedb"
            system "go build --ldflags \"-s -w -X github.com/jzelinskie/cobrautil/v2.Version=$(git describe --always --abbrev=7 --dirty --tags)\" ./cmd/spicedb"
          end
          bin.install "spicedb"
          bash_completion.install "completions/spicedb.bash" => "spicedb"
          zsh_completion.install "completions/spicedb.zsh" => "_spicedb"
          fish_completion.install "completions/spicedb.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/authzed/spicedb/releases/download/v1.33.0/spicedb_1.33.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "903547fcbb45a63e6fa385ce92076855c640dc9dbc6651b09140dee44f60d504"

        def install
          if !File.exists? "spicedb"
            system "go build --ldflags \"-s -w -X github.com/jzelinskie/cobrautil/v2.Version=$(git describe --always --abbrev=7 --dirty --tags)\" ./cmd/spicedb"
          end
          bin.install "spicedb"
          bash_completion.install "completions/spicedb.bash" => "spicedb"
          zsh_completion.install "completions/spicedb.zsh" => "_spicedb"
          fish_completion.install "completions/spicedb.fish"
        end
      end
    end
  end

  head "https://github.com/authzed/spicedb.git", :branch => "main"

  test do
    system "#{bin}/spicedb version"
  end
end
