# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zed < Formula
  desc "manage Authzed from your command line."
  homepage "https://authzed.com/"
  version "0.1.0"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/authzed/zed/releases/download/v0.1.0/zed_0.1.0_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "29e989162276e9ff1c7d7886eabd6c6aab5f51d7ab5d96f78daea092d60b7385"
    end
    if Hardware::CPU.arm?
      url "https://github.com/authzed/zed/releases/download/v0.1.0/zed_0.1.0_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "21f7a7de73d119993780dd0fb81fe2b6b85d874c9593df03290dd153238b14c5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/authzed/zed/releases/download/v0.1.0/zed_0.1.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7f8e1aabd37d49679094d230e70e289c6861c8eeca486f075896502a26223acc"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/authzed/zed/releases/download/v0.1.0/zed_0.1.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "19a1ea18cb84e24fa0f7289aa81da6701985a962489d8bc8ca229cf9b5b4d132"
    end
  end

  head "https://github.com/authzed/zed.git", :branch => "main"

  depends_on "go" => :build

  def install
    if !File.exists? "zed"
      system "go build --ldflags \"-s -w -X github.com/authzed/zed/internal/version.Version=$(git describe --always --abbrev=7 --dirty)\" ./cmd/zed"
    end
    bin.install "zed"
  end

  test do
    system "#{bin}/zed version"
  end
end
