# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zed < Formula
  desc "command-line client for managing SpiceDB"
  homepage "https://github.com/authzed/zed"
  version "0.19.0"
  license "Apache-2.0"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/authzed/zed/releases/download/v0.19.0/zed_0.19.0_darwin_amd64.tar.gz"
      sha256 "f07351cd65470e5bb58e5d613f9e454a5425780f1b04d7c6d3e773b993364922"

      def install
        if build.head?
            versionVar = "github.com/jzelinskie/cobrautil/v2.Version"
            versionCmd = "$(git describe --always --abbrev=7 --dirty --tags)"
            system "go build --ldflags '-s -w -X #{versionVar}=#{versionCmd}' ./cmd/zed"
        end
        bin.install "zed"
        generate_completions_from_executable(bin/"zed", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/authzed/zed/releases/download/v0.19.0/zed_0.19.0_darwin_arm64.tar.gz"
      sha256 "1869d0b5ab25378ead50e08123a45cbded9d8f24ee819f5ad13babae7facff41"

      def install
        if build.head?
            versionVar = "github.com/jzelinskie/cobrautil/v2.Version"
            versionCmd = "$(git describe --always --abbrev=7 --dirty --tags)"
            system "go build --ldflags '-s -w -X #{versionVar}=#{versionCmd}' ./cmd/zed"
        end
        bin.install "zed"
        generate_completions_from_executable(bin/"zed", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/authzed/zed/releases/download/v0.19.0/zed_0.19.0_linux_amd64_gnu.tar.gz"
        sha256 "53665aeb4da81e8ab7c5aea047e22da7c78381c5f7d8b6e2149235ab75d43dc1"

        def install
          if build.head?
              versionVar = "github.com/jzelinskie/cobrautil/v2.Version"
              versionCmd = "$(git describe --always --abbrev=7 --dirty --tags)"
              system "go build --ldflags '-s -w -X #{versionVar}=#{versionCmd}' ./cmd/zed"
          end
          bin.install "zed"
          generate_completions_from_executable(bin/"zed", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/authzed/zed/releases/download/v0.19.0/zed_0.19.0_linux_arm64_gnu.tar.gz"
        sha256 "25788e42059f782f5ca6690fb90345291d27868292d30dd9ba7bb6a0240dd4e1"

        def install
          if build.head?
              versionVar = "github.com/jzelinskie/cobrautil/v2.Version"
              versionCmd = "$(git describe --always --abbrev=7 --dirty --tags)"
              system "go build --ldflags '-s -w -X #{versionVar}=#{versionCmd}' ./cmd/zed"
          end
          bin.install "zed"
          generate_completions_from_executable(bin/"zed", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  head "https://github.com/authzed/zed.git", :branch => "main"

  test do
    system "#{bin}/zed version"
  end
end
